<template>
<main>
    <h1>Lorem ipsum dolor sit amet.</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus cumque iste, accusamus amet cupiditate saepe praesentium. Perspiciatis amet fuga vero eveniet modi corporis accusamus optio voluptatem pariatur delectus reprehenderit inventore consequatur doloribus neque illo reiciendis corrupti quasi in iusto saepe repellendus, non autem. Earum ad minus cupiditate molestiae iusto amet cumque necessitatibus sed itaque velit adipisci explicabo reiciendis, aut architecto fugit suscipit maxime eum inventore corrupti tenetur recusandae sint non eveniet! Voluptatibus, voluptas. Corrupti obcaecati numquam accusantium officiis, voluptatibus dignissimos maiores quia necessitatibus, earum consectetur fugit architecto impedit suscipit! Suscipit praesentium dolor dolores quidem molestiae soluta, qui voluptatibus. Nesciunt, vitae! Accusantium impedit, velit qui ut totam, placeat perferendis voluptate voluptates dolorum omnis quos molestias quaerat voluptatem. Impedit id maiores delectus doloremque nulla sequi aut dolores aliquam quibusdam cupiditate vitae, dolor repellat nostrum, consequatur voluptate facilis a deleniti. Nihil, optio. Inventore dolor unde eos dignissimos suscipit ducimus adipisci. Aliquam ut, numquam voluptatem voluptatibus quis, nam perspiciatis laudantium ducimus vero laboriosam minima? Sunt perferendis animi nesciunt amet ea porro reprehenderit quidem molestiae cupiditate commodi aliquam laudantium at iure fugit minima obcaecati illum error voluptas tenetur, corrupti vitae magnam vel! Voluptate, nemo dignissimos fugit error aut, distinctio ad reprehenderit fuga non quas quae.</p>
    <p>Animi ducimus quas aspernatur similique, quisquam doloremque repudiandae repellat nobis earum delectus iusto laborum eius veniam deleniti dolore dignissimos mollitia natus, nesciunt illo aut dolorum non saepe corporis. Blanditiis modi molestias amet ipsam, repudiandae consequatur a quas voluptate recusandae at voluptatum ea autem, consectetur ex quo nisi. Culpa neque officia doloremque adipisci excepturi. Adipisci in error praesentium quis sint totam asperiores, molestias est quam temporibus hic! Quasi quo nihil repellat, maxime saepe dolor sunt ipsa omnis atque? Voluptate quasi quo perspiciatis aperiam maiores officiis expedita enim adipisci? Ullam quas odio fugit inventore natus, autem nulla illum voluptas sit dicta. Debitis perspiciatis quos, vitae ipsam, earum sint eum sunt similique quo dolorem totam sapiente aspernatur dignissimos pariatur provident numquam qui porro consequatur minima eaque commodi id? Blanditiis beatae deserunt possimus itaque! Tempora, eius suscipit explicabo voluptatibus ullam autem ab, quas animi tempore fuga perspiciatis. Quas optio veniam dolorum nobis voluptas labore nostrum pariatur consectetur dignissimos excepturi temporibus ex dolor quam voluptatem praesentium tempore est, sequi incidunt quia eligendi illo, aperiam non a? Cupiditate inventore ducimus nam laborum, eligendi numquam voluptates voluptatem tenetur adipisci magnam officiis blanditiis illum aliquid fugiat natus corrupti eius recusandae minus incidunt dolor nisi? Architecto, eius fugiat. Tempora.</p>
    <p>Totam voluptate possimus dolore impedit nesciunt corrupti corporis maxime quae at officiis nobis animi quo illo ducimus molestiae obcaecati reprehenderit, pariatur, doloremque ut modi libero? Magnam rem laudantium dicta molestiae dignissimos accusamus consequuntur autem qui delectus expedita iure omnis mollitia nisi, sequi quam non, numquam animi quos, odio possimus recusandae. Natus, sequi? Distinctio est tenetur consequatur similique nihil facere repellendus soluta quis aliquid pariatur placeat adipisci obcaecati excepturi laboriosam reprehenderit, ullam natus perspiciatis reiciendis aspernatur! Quia rem, iusto quibusdam voluptatum dicta commodi ad quas ipsa consectetur ea mollitia provident aliquid tenetur porro non cumque quis natus explicabo blanditiis error reprehenderit ipsam praesentium. Recusandae veniam tempora quas vel neque, odio ab voluptate nisi cupiditate error qui quidem. Nihil distinctio quos fugit nulla voluptas voluptates laboriosam accusamus ullam ratione, sed, tenetur sunt architecto earum dignissimos est quis. Voluptatibus dicta accusantium nisi eos ex, alias corrupti dolor ab accusamus animi fugiat tempora, voluptates sit? Soluta facere voluptate repellat cupiditate. Libero cupiditate autem sint porro minus assumenda beatae veritatis, sunt voluptas expedita quibusdam error ipsam ad itaque quidem tenetur veniam sequi quas qui totam distinctio! Nobis eveniet suscipit animi tempore voluptate beatae? Quod deserunt nihil voluptates magni nisi illum odio modi facilis nobis est!</p>
    <p>Assumenda magnam repellendus, commodi vitae quae sunt beatae vero quia placeat inventore tenetur dolore fugit sint ipsa nemo accusantium neque laborum optio ab atque perspiciatis eveniet? Pariatur voluptates libero veritatis iure saepe sequi et obcaecati ea minus dolor id eligendi aliquid deleniti maxime, ad dolorum laudantium quibusdam sed assumenda facilis! Pariatur soluta quos vero. Eum aliquam deleniti nulla illum hic laboriosam pariatur, voluptate accusamus laudantium, eos quos voluptatibus fuga iste dolorem error, necessitatibus officiis ducimus magni velit. Impedit nostrum, accusamus illum harum ipsam id aut error nisi, vero numquam, voluptate iste! Fugit maxime incidunt quasi debitis esse mollitia possimus rerum veniam nostrum molestiae molestias quod, facere sequi beatae. Repudiandae aperiam reprehenderit sequi impedit fugiat cum blanditiis voluptatem fugit tenetur velit, nisi officiis nam delectus cumque doloremque quidem suscipit voluptatum. Totam ducimus delectus neque beatae sed laborum voluptates laudantium cupiditate qui quisquam, asperiores adipisci laboriosam nobis illum odio velit recusandae autem error officia repudiandae magni illo. Cum consequatur explicabo tempora rem. Aliquid saepe ab iusto voluptatum voluptatibus, perferendis vel eligendi, magni assumenda nulla totam, qui corrupti. Modi quibusdam cum tenetur iure quaerat aliquam autem facilis nam, itaque quod, corrupti nisi sed repudiandae a. Sit magnam qui voluptatem, modi soluta maxime inventore?</p>
    <p>Vitae nemo debitis reprehenderit necessitatibus facere molestiae magnam placeat cupiditate accusantium aliquid blanditiis architecto labore aperiam nesciunt, pariatur ipsa quis inventore cum ipsam? Laudantium saepe iusto doloremque aperiam illum quidem doloribus libero eos, rem blanditiis aut nihil, quis ipsa ad aliquam dolor. Quos, quidem numquam neque quas at a eum vero nisi iure dolores molestiae perspiciatis dolor voluptatibus amet animi suscipit incidunt dignissimos odit? Necessitatibus ducimus, vel vitae aliquid cumque quidem enim similique dicta sit, tempore officia placeat unde fuga laudantium earum amet corrupti, laboriosam sunt ipsum quae. Cum distinctio doloremque, culpa eius corrupti corporis ullam, expedita laboriosam incidunt asperiores nobis? Perspiciatis, odit sequi cum dicta soluta blanditiis necessitatibus, ullam magnam assumenda in veritatis ratione nemo expedita cupiditate sapiente consequatur voluptates adipisci omnis nisi odio recusandae deserunt consequuntur dolorem! Ex voluptatibus eum atque inventore est vitae in obcaecati aperiam eveniet quos, officiis quisquam porro? Autem minus, unde iusto quod aspernatur error quis officia nesciunt animi cumque? Necessitatibus dicta repudiandae libero nisi adipisci inventore animi eos ullam, vitae expedita numquam voluptatibus illo modi exercitationem illum quibusdam suscipit eligendi. Illo laudantium quo corrupti laborum voluptatem tempora facere perspiciatis aliquam architecto? Dolores repellendus et voluptate tenetur nobis necessitatibus pariatur laborum adipisci saepe incidunt.</p>
</main>
</template>

<script>
    export default {
    name: "Home",
}
</script>

<style scoped>
main {
    font-size: 18px;
}
</style>