name: Publish to Docker
on:
  release:
    types: [published]
permissions:
  packages: write
  contents: read
jobs:
  publish-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/client
          tags: type=match,pattern=v(.*),group=1
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: ./packages/client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  # publish-server:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     # Add your test steps here if needed...
  #     - name: Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ghcr.io/${{ github.repository }}/server
  #         tags: type=sha
  #     - name: Login to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build container
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: ./packages/server
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
